// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate/introspect need a direct (non-pooled) connection to Supabase Postgres.
  // The app's runtime PrismaClient (lib/prisma.ts) connects separately via the
  // pooled DATABASE_URL through a driver adapter.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
